remote_theme: pages-themes/minimal@v0.2.0
title: Nibedita's Portfolio
description: AI/ML Explorer | MSc in ML/AI | Portfolio site highlighting ML/AI expertise and practical deployments
theme: jekyll-theme-minimal
favicon: /favicon.ico
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
